import { BotProfile } from "@/types/chess";

export const BOTS: BotProfile[] = [
  {
    id: "martin",
    name: "Friendly Martin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Martin&backgroundColor=f8d250",
    elo: 250,
    description: "A kind-hearted beginner. He often wonders why the little horsies move in L patterns but enjoys every second of it.",
    skillLevel: 0,
    thinkTime: 1500,
  },
  {
    id: "oliver",
    name: "Oliver Gambiteer",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Oliver&backgroundColor=65c9ff",
    elo: 600,
    description: "A risky player who believes that a game without a sacrifice is a game wasted. He loves the King's Gambit.",
    skillLevel: 2,
    thinkTime: 1200,
  },
  {
    id: "elara",
    name: "Elara Tactical",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Elara&backgroundColor=ffadad",
    elo: 1000,
    description: "Sharp, precise, and dangerous. She spots forks from across the room and never misses a back-rank mate.",
    skillLevel: 6,
    thinkTime: 900,
  },
  {
    id: "viktor",
    name: "Old Master Viktor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Viktor&backgroundColor=d1d1d1",
    elo: 1400,
    description: "Decades of experience has taught him that patience is a virtue. He excels in the English Opening and dry endgames.",
    skillLevel: 9,
    thinkTime: 800,
  },
  {
    id: "sia",
    name: "Sia Speedster",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sia&backgroundColor=ffd6a5",
    elo: 1800,
    description: "Blitz is her middle name. She plays moves instantly to pressure your clock, forcing you into early blunders.",
    skillLevel: 13,
    thinkTime: 200,
  },
  {
    id: "stella",
    name: "Stella Strategist",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Stella&backgroundColor=bdb2ff",
    elo: 2300,
    description: "She sees the board as a complex web of imbalances. Her moves might look mysterious until you're completely paralyzed.",
    skillLevel: 17,
    thinkTime: 400,
  },
  {
    id: "nova",
    name: "Nova Prototype",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Nova&backgroundColor=9bf6ff",
    elo: 2800,
    description: "An experimental neural network. It sometimes finds moves that 'defy human logic' but are crushing in their efficiency.",
    skillLevel: 19,
    thinkTime: 150,
  },
  {
    id: "magnus_bot",
    name: "The Beast 10.0",
    avatar: "https://api.dicebear.com/7.x/bottts/svg?seed=Beast&backgroundColor=ffadad",
    elo: 3500,
    description: "The absolute pinnacle of Stockfish integration. It does not play chess; it solves it.",
    skillLevel: 20,
    thinkTime: 50,
  },
];
